steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thematic-metric-381904/github.com/searce-tirth/blog-app:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thematic-metric-381904/github.com/searce-tirth/blog-app:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    gcloud run deploy blog-app \
    --image gcr.io/thematic-metric-381904/github.com/searce-tirth/blog-app:$COMMIT_SHA \
    --region us-central1 \
    --allow-unauthenticated
    
images:
- 'gcr.io/thematic-metric-381904/github.com/searce-tirth/blog-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
